import type { Kpi } from "../dashboardModel";

const KPI_TOOLTIPS: Record<string, string> = {
  total: "Total aggregated tokens processed across your active workspace. Prompt content is excluded.",
  input: "Tokens sent to the model (context, prompt, history, repo files).",
  output: "Tokens generated by the model (responses, code, plans).",
  latency: "Average response time in milliseconds. Only runs that report execution duration are included. Displays 'Unavailable' if no timing data is exposed."
};

export function KpiTile({ index, kpi }: { index: number; kpi: Kpi }) {
  const progressWidth =
    kpi.id === "input" ? "71%" : kpi.id === "output" ? "29%" : null;

  return (
    <article className={`metricTile metricTone${index + 1}`}>
      <div className="metricTileHeader">
        <p>{kpi.label}</p>
        <span className="infoIcon" title={KPI_TOOLTIPS[kpi.id]}>ⓘ</span>
      </div>
      <strong>{kpi.value}</strong>
      <span>{kpi.detail}</span>
      {progressWidth ? (
        <div className="metricProgress" aria-hidden="true">
          <span style={{ width: progressWidth }} />
        </div>
      ) : null}
    </article>
  );
}
