import Foundation

extension PreferencesL10n {
    static let preferencesJapaneseTextPart1: [PreferencesTextKey: String] = [
            .preferencesWindowTitle: "Spill 設定",
            .general: "一般",
            .menuBar: "メニューバー",
            .menuBarAndNotch: "メニューバー",
            .tokenMetering: "トークン計測",
            .windowManagement: "ウィンドウ管理",
            .statusAndCaffeine: "状態とカフェイン",
            .developerOptions: "開発者オプション",
            .developerOptionsDetail: "保存データを変えずに初回状態を確認するデバッグ専用オプションです。",
            .debugOnly: "デバッグのみ",
            .checking: "確認中",
            .checkForUpdates: "アップデートを確認",
            .launchSettings: "起動設定",
            .launchAtLogin: "ログイン時に起動",
            .launchAtLoginUnavailable: "Spill を .app バンドルとしてパッケージ化すると、ログイン時起動を使用できます。",
            .dashboardOnboardingPreview: "ダッシュボードの初回表示プレビュー",
            .dashboardOnboardingPreviewDetail: "ローカルのアクションとトークン使用量データを変えずに、パネルを初回状態で表示します。",
            .aiDashboardOnboardingPreview: "Spill - AI Token Metering の初回表示プレビュー",
            .aiDashboardOnboardingPreviewDetail: "トークン記録を削除せず、Spill - AI Token Metering とパネルのトークンカードを設定プレビュー状態で表示します。",
            .languageSettings: "言語設定",
            .appLanguage: "アプリの言語",
            .language: "言語",
            .appearanceSettings: "外観",
            .appearanceTheme: "テーマ",
            .appearanceThemeDetail: "パネル、設定ウィンドウ、AIダッシュボードに適用されます。",
            .appearanceSystem: "システム",
            .appearanceLight: "ライト",
            .appearanceDark: "ダーク",
            .permissionsAndDiagnostics: "権限と診断",
            .updates: "アップデート",
            .menuBarIconAnimation: "メニューバーアイコンとアニメーション",
            .useSpillAnimation: "Spill アニメーションを使用",
            .menuBarTriggerIcon: "メニューバートリガーアイコン",
            .globalShortcut: "グローバルショートカット",
            .keyboardShortcut: "キーボードショートカット",
            .windowSnapShortcuts: "ウィンドウスナップショートカット",
            .statusModules: "状態モジュール",
            .caffeineSettings: "カフェイン設定",
            .feedbackContribution: "フィードバックと貢献",
            .githubOpenSource: "GitHub オープンソース",
            .openSourceLicense: "Spill は MIT ライセンスのオープンソースアプリです。",
            .preview: "プレビュー",
            .currentVersion: "現在のバージョン",
            .copied: "コピー済み",
            .copyInstallCommand: "インストールコマンドをコピー",
            .notes: "ノート",
            .terminalInstallCommand: "ターミナルインストールコマンド",
            .checkingForUpdates: "アップデートを確認中...",
            .upToDate: "Spill は最新です (%@)。",
            .updateNow: "今すぐアップデート",
            .openInstaller: "インストーラーを開く",
            .downloadDMG: "DMG をダウンロード",
            .dashboardChecksInApp: "アップデート状態は 1 日 1 回確認します。ここでアップデート確認を使うとアプリ内アップデーターを開始します。",
            .dashboardChecksGitHub: "アップデート状態は 1 日 1 回確認します。手動確認は最新の GitHub リリース情報を使用します。",
            .updateInsideApp: "バージョン %@ が利用可能です。アプリ内でアップデートしてください。",
            .updateWithInstaller: "バージョン %@ が利用可能です。署名済みインストーラーパッケージを開いて更新してください。",
            .updateWithCommandOrDMG: "バージョン %@ が利用可能です。ターミナルコマンドをコピーするか DMG をダウンロードしてください。",
            .unsupportedVersion: "バージョン %@ には macOS %@ が必要です。",
    ]
}
