import Foundation

extension PreferencesL10n {
    static let preferencesEnglishTextPart2: [PreferencesTextKey: String] = [
            .newerThanVersion: "newer than %@",
            .accessibilityActive: "Accessibility Active",
            .accessibilityNeeded: "Accessibility Needed",
            .on: "ON",
            .off: "OFF",
            .openPanel: "Open Panel",
            .scanning: "Scanning",
            .refreshScanner: "Refresh Scanner",
            .accessibilityPermissionDetail: "Spill needs Accessibility permission to discover and activate menu bar items owned by other apps.",
            .accessibilityPermissionRelaunch: "After granting permission in System Settings, relaunch Spill if it still shows as inactive.",
            .requestAccess: "Request Access",
            .systemSettings: "System Settings",
            .recheck: "Recheck",
            .relaunch: "Relaunch",
            .permissionDiagnostics: "Permission Diagnostics",
            .itemCount: "Items",
            .caffeine: "Caffeine",
            .defaultDuration: "Default duration",
            .keepDisplayAwakeDuringCaffeine: "Keep display awake during Caffeine",
            .showRemainingTimeInClockArea: "Show remaining time in clock area",
            .warningShowNeverDuration: "Warning: show unlimited duration",
            .neverCaffeineWarning: "Unlimited keeps Caffeine active until you stop it manually.",
            .panelStatus: "Panel Status",
            .panelStatusDetail: "Controls the status cards inside the Spill panel.",
            .aggregate: "Aggregate",
            .statusValueBold: "Bold Values",
            .statusFontDesign: "Value Font",
            .statusValueSize: "Value Size",
            .panelSectionSpacing: "Panel Section Spacing",
            .fontDefault: "Default",
            .fontRounded: "Rounded",
            .fontMono: "Mono",
            .clockAreaStatus: "Clock Area",
            .clockAreaStatusDetail: "Shown next to the macOS clock. Choose Off, Text, or Chart for each system metric.",
            .clockAreaCompactMode: "Compact Status Values",
            .clockAreaCompactModeDetail: "Use tighter icon/value rendering only when you choose a compact menu bar.",
            .clockAreaSplitGroups: "Split Status Groups",
            .clockAreaSplitGroupsDetail: "Experimental: separates Main, System, and AI. macOS may still leave empty space or hide other menu extras.",
            .clockAreaTextBold: "Bold Clock Text",
            .clockAreaTextSize: "Clock Text Size",
            .spillGlance: "Spill Glance",
            .spillGlanceDetail: "Shows All Today and Work Type, plus the AI tools you choose, in one movable horizontal glass surface.",
            .showSpillGlance: "Show Spill Glance",
            .spillGlanceDisplay: "Display",
            .spillGlanceDisplayAll: "All",
            .spillGlanceDisplayTicker: "Ticker",
            .spillGlanceReactiveRotation: "Reactive View",
            .spillGlanceReactiveRotationDetail: "Roll only what just changed, then settle back to today's total. Turn this off to cycle everything on a fixed schedule instead.",
            .spillGlanceShowInFullScreen: "Show in Full Screen",
            .spillGlanceShowInFullScreenDetail: "Off by default so Glance does not cover full-screen apps.",
            .spillGlanceWorkRotation: "Rotate Work Type",
            .spillGlanceWorkRotationDetail: "Let the Work slot change types. Reactive View shows the type that just moved; with it off, Ticker cycles today's Work Types in order. Turn this off to keep only the highest-usage Work Type.",
            .spillGlanceCodex: "Codex",
            .spillGlanceClaude: "Claude",
            .spillGlanceAntigravity: "Antigravity",
            .layout: "Layout",
            .decimals: "CPU/MEM Decimals",
            .highlight: "High Usage",
            .inline: "Horizontal",
            .stacked: "Vertical",
            .text: "Text",
            .chart: "Chart",
            .iconOnly: "Icon Only",
            .bundleID: "Bundle ID",
            .bundle: "Bundle",
            .executable: "Executable",
            .pid: "PID",
            .appBundleLaunch: "App bundle launch",
            .axTrusted: "AX trusted"
    ]
}
