import Foundation

extension PreferencesL10n {
    static let preferencesEnglishTextPart2: [PreferencesTextKey: String] = [
            .newerThanVersion: "newer than %@",
            .accessibilityActive: "Accessibility Active",
            .accessibilityNeeded: "Accessibility Needed",
            .on: "ON",
            .off: "OFF",
            .openPanel: "Open Panel",
            .scanning: "Scanning",
            .refreshScanner: "Refresh Scanner",
            .accessibilityPermissionDetail: "Spill needs Accessibility permission to discover and activate menu bar items owned by other apps.",
            .accessibilityPermissionRelaunch: "After granting permission in System Settings, relaunch Spill if it still shows as inactive.",
            .requestAccess: "Request Access",
            .systemSettings: "System Settings",
            .recheck: "Recheck",
            .relaunch: "Relaunch",
            .permissionDiagnostics: "Permission Diagnostics",
            .itemCount: "Items",
            .caffeine: "Caffeine",
            .defaultDuration: "Default duration",
            .keepDisplayAwakeDuringCaffeine: "Keep display awake during Caffeine",
            .showRemainingTimeInClockArea: "Show remaining time in clock area",
            .warningShowNeverDuration: "Warning: show unlimited duration",
            .neverCaffeineWarning: "Unlimited keeps Caffeine active until you stop it manually.",
            .panelStatus: "Panel Status",
            .panelStatusDetail: "Controls the status cards inside the Spill panel.",
            .aggregate: "Aggregate",
            .statusValueBold: "Bold Values",
            .statusFontDesign: "Value Font",
            .statusValueSize: "Value Size",
            .panelSectionSpacing: "Panel Section Spacing",
            .fontDefault: "Default",
            .fontRounded: "Rounded",
            .fontMono: "Mono",
            .clockAreaStatus: "Clock Area",
            .clockAreaStatusDetail: "Shown next to the macOS clock. Clicking AI opens Spill - AI Token Metering.",
            .clockAreaCompactMode: "Compact Status Values",
            .clockAreaCompactModeDetail: "Use tighter icon/value rendering only when you choose a compact menu bar.",
            .clockAreaSplitGroups: "Split Status Groups",
            .clockAreaSplitGroupsDetail: "Experimental: separates Main, System, and AI. macOS may still leave empty space or hide other menu extras.",
            .clockAreaTextBold: "Bold Clock Text",
            .clockAreaTextSize: "Clock Text Size",
            .layout: "Layout",
            .decimals: "CPU/MEM Decimals",
            .highlight: "High Usage",
            .inline: "Horizontal",
            .stacked: "Vertical",
            .iconOnly: "Icon Only",
            .bundleID: "Bundle ID",
            .bundle: "Bundle",
            .executable: "Executable",
            .pid: "PID",
            .appBundleLaunch: "App bundle launch",
            .axTrusted: "AX trusted"
    ]
}
