import Foundation

struct PreferencesTextKey: RawRepresentable, Hashable, Sendable {
    let rawValue: String

    init(rawValue: String) {
        self.rawValue = rawValue
    }
}

extension PreferencesTextKey {
    static let preferencesWindowTitle = Self(rawValue: "preferencesWindowTitle")
    static let general = Self(rawValue: "general")
    static let menuBar = Self(rawValue: "menuBar")
    static let menuBarAndNotch = Self(rawValue: "menuBarAndNotch")
    static let tokenMetering = Self(rawValue: "tokenMetering")
    static let windowManagement = Self(rawValue: "windowManagement")
    static let statusAndCaffeine = Self(rawValue: "statusAndCaffeine")
    static let developerOptions = Self(rawValue: "developerOptions")
    static let developerOptionsDetail = Self(rawValue: "developerOptionsDetail")
    static let debugOnly = Self(rawValue: "debugOnly")
    static let checking = Self(rawValue: "checking")
    static let checkForUpdates = Self(rawValue: "checkForUpdates")
    static let launchSettings = Self(rawValue: "launchSettings")
    static let launchAtLogin = Self(rawValue: "launchAtLogin")
    static let launchAtLoginUnavailable = Self(rawValue: "launchAtLoginUnavailable")
    static let dashboardOnboardingPreview = Self(rawValue: "dashboardOnboardingPreview")
    static let dashboardOnboardingPreviewDetail = Self(rawValue: "dashboardOnboardingPreviewDetail")
    static let aiDashboardOnboardingPreview = Self(rawValue: "aiDashboardOnboardingPreview")
    static let aiDashboardOnboardingPreviewDetail = Self(rawValue: "aiDashboardOnboardingPreviewDetail")
    static let languageSettings = Self(rawValue: "languageSettings")
    static let appLanguage = Self(rawValue: "appLanguage")
    static let language = Self(rawValue: "language")
    static let appearanceSettings = Self(rawValue: "appearanceSettings")
    static let appearanceTheme = Self(rawValue: "appearanceTheme")
    static let appearanceThemeDetail = Self(rawValue: "appearanceThemeDetail")
    static let appearanceSystem = Self(rawValue: "appearanceSystem")
    static let appearanceLight = Self(rawValue: "appearanceLight")
    static let appearanceDark = Self(rawValue: "appearanceDark")
    static let permissionsAndDiagnostics = Self(rawValue: "permissionsAndDiagnostics")
    static let updates = Self(rawValue: "updates")
    static let menuBarIconAnimation = Self(rawValue: "menuBarIconAnimation")
    static let useSpillAnimation = Self(rawValue: "useSpillAnimation")
    static let menuBarTriggerIcon = Self(rawValue: "menuBarTriggerIcon")
    static let globalShortcut = Self(rawValue: "globalShortcut")
    static let keyboardShortcut = Self(rawValue: "keyboardShortcut")
    static let windowSnapShortcuts = Self(rawValue: "windowSnapShortcuts")
    static let statusModules = Self(rawValue: "statusModules")
    static let caffeineSettings = Self(rawValue: "caffeineSettings")
    static let feedbackContribution = Self(rawValue: "feedbackContribution")
    static let githubOpenSource = Self(rawValue: "githubOpenSource")
    static let openSourceLicense = Self(rawValue: "openSourceLicense")
    static let preview = Self(rawValue: "preview")
    static let currentVersion = Self(rawValue: "currentVersion")
    static let copied = Self(rawValue: "copied")
    static let copyInstallCommand = Self(rawValue: "copyInstallCommand")
    static let notes = Self(rawValue: "notes")
    static let terminalInstallCommand = Self(rawValue: "terminalInstallCommand")
    static let checkingForUpdates = Self(rawValue: "checkingForUpdates")
    static let upToDate = Self(rawValue: "upToDate")
    static let updateNow = Self(rawValue: "updateNow")
    static let openInstaller = Self(rawValue: "openInstaller")
    static let downloadDMG = Self(rawValue: "downloadDMG")
    static let dashboardChecksInApp = Self(rawValue: "dashboardChecksInApp")
    static let dashboardChecksGitHub = Self(rawValue: "dashboardChecksGitHub")
    static let updateInsideApp = Self(rawValue: "updateInsideApp")
    static let updateWithInstaller = Self(rawValue: "updateWithInstaller")
    static let updateWithCommandOrDMG = Self(rawValue: "updateWithCommandOrDMG")
    static let unsupportedVersion = Self(rawValue: "unsupportedVersion")
    static let newerThanVersion = Self(rawValue: "newerThanVersion")
    static let accessibilityActive = Self(rawValue: "accessibilityActive")
    static let accessibilityNeeded = Self(rawValue: "accessibilityNeeded")
}

extension PreferencesTextKey {
    static let on = Self(rawValue: "on")
    static let off = Self(rawValue: "off")
    static let openPanel = Self(rawValue: "openPanel")
    static let scanning = Self(rawValue: "scanning")
    static let refreshScanner = Self(rawValue: "refreshScanner")
    static let accessibilityPermissionDetail = Self(rawValue: "accessibilityPermissionDetail")
    static let accessibilityPermissionRelaunch = Self(rawValue: "accessibilityPermissionRelaunch")
    static let requestAccess = Self(rawValue: "requestAccess")
    static let systemSettings = Self(rawValue: "systemSettings")
    static let recheck = Self(rawValue: "recheck")
    static let relaunch = Self(rawValue: "relaunch")
    static let permissionDiagnostics = Self(rawValue: "permissionDiagnostics")
    static let itemCount = Self(rawValue: "itemCount")
    static let caffeine = Self(rawValue: "caffeine")
    static let defaultDuration = Self(rawValue: "defaultDuration")
    static let keepDisplayAwakeDuringCaffeine = Self(rawValue: "keepDisplayAwakeDuringCaffeine")
    static let showRemainingTimeInClockArea = Self(rawValue: "showRemainingTimeInClockArea")
    static let warningShowNeverDuration = Self(rawValue: "warningShowNeverDuration")
    static let neverCaffeineWarning = Self(rawValue: "neverCaffeineWarning")
    static let panelStatus = Self(rawValue: "panelStatus")
    static let panelStatusDetail = Self(rawValue: "panelStatusDetail")
    static let aggregate = Self(rawValue: "aggregate")
    static let statusValueBold = Self(rawValue: "statusValueBold")
    static let statusFontDesign = Self(rawValue: "statusFontDesign")
    static let statusValueSize = Self(rawValue: "statusValueSize")
    static let panelSectionSpacing = Self(rawValue: "panelSectionSpacing")
    static let fontDefault = Self(rawValue: "fontDefault")
    static let fontRounded = Self(rawValue: "fontRounded")
    static let fontMono = Self(rawValue: "fontMono")
    static let clockAreaStatus = Self(rawValue: "clockAreaStatus")
    static let clockAreaStatusDetail = Self(rawValue: "clockAreaStatusDetail")
    static let clockAreaCompactMode = Self(rawValue: "clockAreaCompactMode")
    static let clockAreaCompactModeDetail = Self(rawValue: "clockAreaCompactModeDetail")
    static let clockAreaSplitGroups = Self(rawValue: "clockAreaSplitGroups")
    static let clockAreaSplitGroupsDetail = Self(rawValue: "clockAreaSplitGroupsDetail")
    static let clockAreaTextBold = Self(rawValue: "clockAreaTextBold")
    static let clockAreaTextSize = Self(rawValue: "clockAreaTextSize")
    static let layout = Self(rawValue: "layout")
    static let decimals = Self(rawValue: "decimals")
    static let highlight = Self(rawValue: "highlight")
    static let inline = Self(rawValue: "inline")
    static let stacked = Self(rawValue: "stacked")
    static let text = Self(rawValue: "text")
    static let chart = Self(rawValue: "chart")
    static let iconOnly = Self(rawValue: "iconOnly")
    static let bundleID = Self(rawValue: "bundleID")
    static let bundle = Self(rawValue: "bundle")
    static let executable = Self(rawValue: "executable")
    static let pid = Self(rawValue: "pid")
    static let appBundleLaunch = Self(rawValue: "appBundleLaunch")
    static let axTrusted = Self(rawValue: "axTrusted")
}
