import Foundation

extension PreferencesL10n {
    static let preferencesEnglishTextPart1: [PreferencesTextKey: String] = [
            .preferencesWindowTitle: "Spill Preferences",
            .general: "General",
            .menuBar: "Menu Bar",
            .menuBarAndNotch: "Menu Bar",
            .tokenMetering: "Token Metering",
            .windowManagement: "Window Management",
            .statusAndCaffeine: "Status & Caffeine",
            .developerOptions: "Developer Options",
            .developerOptionsDetail: "Debug-only preview switches for checking first-run states without changing saved data.",
            .debugOnly: "Debug only",
            .checking: "Checking",
            .checkForUpdates: "Check for Updates",
            .launchSettings: "Launch Settings",
            .launchAtLogin: "Launch at Login",
            .launchAtLoginUnavailable: "Launch at Login is available after packaging Spill as a .app bundle.",
            .dashboardOnboardingPreview: "Dashboard onboarding preview",
            .dashboardOnboardingPreviewDetail: "Shows the panel as a first-run preview without changing local actions or token usage data.",
            .aiDashboardOnboardingPreview: "Spill - AI Token Metering onboarding preview",
            .aiDashboardOnboardingPreviewDetail: "Shows Spill - AI Token Metering and the panel token card in setup preview without deleting token records.",
            .languageSettings: "Language Settings",
            .appLanguage: "App Language",
            .language: "Language",
            .appearanceSettings: "Appearance",
            .appearanceTheme: "Theme",
            .appearanceThemeDetail: "Applies to the panel, settings window, and AI dashboard.",
            .appearanceSystem: "System",
            .appearanceLight: "Light",
            .appearanceDark: "Dark",
            .permissionsAndDiagnostics: "Permissions & Diagnostics",
            .updates: "Updates",
            .menuBarIconAnimation: "Menu Bar Icon & Animation",
            .useSpillAnimation: "Use spill animation",
            .menuBarTriggerIcon: "Menu bar trigger icon",
            .globalShortcut: "Global Shortcut",
            .keyboardShortcut: "Keyboard shortcut",
            .windowSnapShortcuts: "Window Snap Shortcuts",
            .statusModules: "Status Modules",
            .caffeineSettings: "Caffeine Settings",
            .feedbackContribution: "Feedback & Contribution",
            .githubOpenSource: "GitHub Open Source",
            .openSourceLicense: "Spill is proudly open-source under the MIT license.",
            .preview: "Preview",
            .currentVersion: "Current version",
            .copied: "Copied",
            .copyInstallCommand: "Copy Install Command",
            .notes: "Notes",
            .terminalInstallCommand: "Terminal install command",
            .checkingForUpdates: "Checking for updates...",
            .upToDate: "Spill is up to date (%@).",
            .updateNow: "Update Now",
            .openInstaller: "Open Installer",
            .downloadDMG: "Download DMG",
            .dashboardChecksInApp: "Update status checks once per day. Use Check for Updates here to start the in-app updater.",
            .dashboardChecksGitHub: "Update status checks once per day. Manual checks use the latest GitHub release metadata.",
            .updateInsideApp: "Version %@ is available. Update inside the app.",
            .updateWithInstaller: "Version %@ is available. Open the signed installer package to update.",
            .updateWithCommandOrDMG: "Version %@ is available. Copy the terminal command or download the DMG.",
            .unsupportedVersion: "Version %@ requires macOS %@.",
    ]
}
