import Foundation

extension PreferencesL10n {
    static let preferencesKoreanTextPart1: [PreferencesTextKey: String] = [
            .preferencesWindowTitle: "Spill 설정",
            .general: "일반",
            .menuBar: "메뉴 막대",
            .menuBarAndNotch: "메뉴 막대",
            .tokenMetering: "토큰 미터링",
            .windowManagement: "윈도우 관리",
            .statusAndCaffeine: "상태 및 카페인",
            .developerOptions: "개발자 옵션",
            .developerOptionsDetail: "저장된 데이터는 유지한 채 첫 실행 상태를 확인하는 디버그 전용 옵션입니다.",
            .debugOnly: "디버그 전용",
            .checking: "확인 중",
            .checkForUpdates: "업데이트 확인",
            .launchSettings: "실행 설정",
            .launchAtLogin: "로그인 시 실행",
            .launchAtLoginUnavailable: "Spill이 .app 번들로 패키징된 뒤 로그인 시 실행을 사용할 수 있습니다.",
            .dashboardOnboardingPreview: "대시보드 첫 실행 미리보기",
            .dashboardOnboardingPreviewDetail: "로컬 액션과 토큰 사용량 데이터는 유지한 채 패널을 첫 실행 상태로 보여줍니다.",
            .aiDashboardOnboardingPreview: "Spill - AI Token Metering 첫 실행 미리보기",
            .aiDashboardOnboardingPreviewDetail: "토큰 기록은 삭제하지 않고 Spill - AI Token Metering과 패널 토큰 카드를 설정 미리보기 상태로 보여줍니다.",
            .languageSettings: "언어 설정",
            .appLanguage: "앱 언어",
            .language: "언어",
            .permissionsAndDiagnostics: "권한 및 진단",
            .updates: "업데이트",
            .menuBarIconAnimation: "메뉴 막대 아이콘 및 애니메이션",
            .useSpillAnimation: "Spill 애니메이션 사용",
            .menuBarTriggerIcon: "메뉴 막대 트리거 아이콘",
            .globalShortcut: "전역 단축키",
            .keyboardShortcut: "키보드 단축키",
            .windowSnapShortcuts: "윈도우 스냅 단축키",
            .statusModules: "상태 모듈",
            .caffeineSettings: "카페인 설정",
            .feedbackContribution: "피드백 및 기여",
            .githubOpenSource: "GitHub 오픈소스",
            .openSourceLicense: "Spill은 MIT 라이선스의 오픈소스 앱입니다.",
            .preview: "미리보기",
            .currentVersion: "현재 버전",
            .copied: "복사됨",
            .copyInstallCommand: "설치 명령 복사",
            .notes: "노트",
            .terminalInstallCommand: "터미널 설치 명령",
            .checkingForUpdates: "업데이트 확인 중...",
            .upToDate: "Spill은 최신 상태입니다 (%@).",
            .updateNow: "지금 업데이트",
            .openInstaller: "설치 프로그램 열기",
            .downloadDMG: "DMG 다운로드",
            .dashboardChecksInApp: "업데이트 상태는 하루에 한 번 확인합니다. 여기서 업데이트 확인을 누르면 앱 내 업데이터를 시작합니다.",
            .dashboardChecksGitHub: "업데이트 상태는 하루에 한 번 확인합니다. 수동 확인은 최신 GitHub 릴리스 정보를 사용합니다.",
            .updateInsideApp: "버전 %@을 사용할 수 있습니다. 앱에서 업데이트하세요.",
            .updateWithInstaller: "버전 %@을 사용할 수 있습니다. 서명된 설치 패키지를 열어 업데이트하세요.",
            .updateWithCommandOrDMG: "버전 %@을 사용할 수 있습니다. 터미널 명령을 복사하거나 DMG를 다운로드하세요.",
            .unsupportedVersion: "버전 %@은 macOS %@ 이상이 필요합니다.",
    ]
}
