import Foundation

extension PreferencesL10n {
    static let preferencesKoreanTextPart2: [PreferencesTextKey: String] = [
            .newerThanVersion: "%@보다 최신 버전",
            .accessibilityActive: "손쉬운 사용 활성",
            .accessibilityNeeded: "손쉬운 사용 권한 필요",
            .on: "켬",
            .off: "끔",
            .openPanel: "패널 열기",
            .scanning: "스캔 중",
            .refreshScanner: "스캐너 새로고침",
            .accessibilityPermissionDetail: "Spill이 다른 앱의 메뉴 막대 항목을 찾고 활성화하려면 손쉬운 사용 권한이 필요합니다.",
            .accessibilityPermissionRelaunch: "시스템 설정에서 권한을 부여한 뒤에도 비활성으로 표시되면 Spill을 다시 실행하세요.",
            .requestAccess: "권한 요청",
            .systemSettings: "시스템 설정",
            .recheck: "다시 확인",
            .relaunch: "다시 실행",
            .permissionDiagnostics: "권한 진단",
            .itemCount: "항목",
            .caffeine: "카페인",
            .defaultDuration: "기본 지속 시간",
            .keepDisplayAwakeDuringCaffeine: "카페인 중 디스플레이 깨우기 유지",
            .showRemainingTimeInClockArea: "시계 영역에 남은 시간 표시",
            .warningShowNeverDuration: "경고: '무제한' 시간 표시",
            .neverCaffeineWarning: "무제한은 수동으로 중지할 때까지 카페인을 활성 상태로 유지합니다.",
            .panelStatus: "패널 상태",
            .panelStatusDetail: "Spill 패널 안의 상태 카드 표시를 조정합니다.",
            .aggregate: "집계",
            .statusValueBold: "값 굵게",
            .statusFontDesign: "값 글꼴",
            .statusValueSize: "값 크기",
            .panelSectionSpacing: "패널 섹션 간격",
            .fontDefault: "기본",
            .fontRounded: "둥근",
            .fontMono: "고정폭",
            .clockAreaStatus: "시계 옆 상태",
            .clockAreaStatusDetail: "macOS 시계 옆에 표시됩니다. 시스템 지표마다 끔, 텍스트 또는 차트를 선택할 수 있습니다.",
            .clockAreaCompactMode: "상태값 축소 표시",
            .clockAreaCompactModeDetail: "선택한 경우에만 아이콘과 값을 더 촘촘한 메뉴 막대 형태로 표시합니다.",
            .clockAreaSplitGroups: "상태 그룹 분리",
            .clockAreaSplitGroupsDetail: "실험적 기능: 메인, 시스템, AI를 분리합니다. macOS가 여전히 빈 공간을 남기거나 다른 메뉴 막대 항목을 숨길 수 있습니다.",
            .clockAreaTextBold: "시계 옆 텍스트 굵게",
            .clockAreaTextSize: "시계 옆 텍스트 크기",
            .spillGlance: "Spill 글랜스",
            .spillGlanceDetail: "오늘 전체 사용량과 작업 유형, 선택한 AI 도구를 이동 가능한 하나의 가로 글래스 화면에 표시합니다.",
            .showSpillGlance: "Spill 글랜스 표시",
            .spillGlanceDisplay: "표시 방식",
            .spillGlanceDisplayAll: "모두",
            .spillGlanceDisplayTicker: "전광판",
            .spillGlanceReactiveRotation: "반응형으로 보기",
            .spillGlanceReactiveRotationDetail: "방금 바뀐 항목만 굴러가고, 조용해지면 오늘 총량으로 돌아옵니다. 끄면 정해진 간격으로 전체를 순환합니다.",
            .spillGlanceShowInFullScreen: "전체 화면에서도 표시",
            .spillGlanceShowInFullScreenDetail: "전체 화면 앱을 가리지 않도록 기본값은 꺼져 있습니다.",
            .spillGlanceWorkRotation: "작업 유형 순환",
            .spillGlanceWorkRotationDetail: "Work 칸이 작업 유형을 바꾸도록 합니다. 반응형으로 보기에서는 방금 움직인 유형을 보여주고, 끄면 전광판이 오늘의 작업 유형을 순서대로 순환합니다. 이 항목을 끄면 사용량이 가장 높은 유형만 표시합니다.",
            .spillGlanceCodex: "Codex",
            .spillGlanceClaude: "Claude",
            .spillGlanceAntigravity: "Antigravity",
            .layout: "레이아웃",
            .decimals: "CPU/MEM 소수점",
            .highlight: "높은 사용량",
            .inline: "가로",
            .stacked: "세로",
            .text: "텍스트",
            .chart: "차트",
            .iconOnly: "아이콘만",
            .bundleID: "번들 ID",
            .bundle: "번들",
            .executable: "실행 파일",
            .pid: "PID",
            .appBundleLaunch: "앱 번들 실행",
            .axTrusted: "AX 신뢰됨"
    ]
}
