import Foundation

extension PreferencesL10n {
    static let preferencesJapaneseTextPart2: [PreferencesTextKey: String] = [
            .newerThanVersion: "%@ より新しいバージョン",
            .accessibilityActive: "アクセシビリティ有効",
            .accessibilityNeeded: "アクセシビリティ権限が必要",
            .on: "オン",
            .off: "オフ",
            .openPanel: "パネルを開く",
            .scanning: "スキャン中",
            .refreshScanner: "スキャナーを更新",
            .accessibilityPermissionDetail: "Spill が他のアプリのメニューバー項目を検出して有効化するにはアクセシビリティ権限が必要です。",
            .accessibilityPermissionRelaunch: "システム設定で権限を付与した後も無効と表示される場合は Spill を再起動してください。",
            .requestAccess: "アクセスを要求",
            .systemSettings: "システム設定",
            .recheck: "再確認",
            .relaunch: "再起動",
            .permissionDiagnostics: "権限診断",
            .itemCount: "項目",
            .caffeine: "カフェイン",
            .defaultDuration: "既定の時間",
            .keepDisplayAwakeDuringCaffeine: "カフェイン中はディスプレイを起動したままにする",
            .showRemainingTimeInClockArea: "時計エリアに残り時間を表示",
            .warningShowNeverDuration: "警告: 無期限の時間を表示",
            .neverCaffeineWarning: "無期限は手動で停止するまでカフェインを有効にします。",
            .panelStatus: "パネル状態",
            .panelStatusDetail: "Spill パネル内の状態カード表示を調整します。",
            .aggregate: "集計",
            .statusValueBold: "値を太字",
            .statusFontDesign: "値のフォント",
            .statusValueSize: "値のサイズ",
            .panelSectionSpacing: "パネルセクション間隔",
            .fontDefault: "既定",
            .fontRounded: "丸ゴシック",
            .fontMono: "等幅",
            .clockAreaStatus: "時計横の状態",
            .clockAreaStatusDetail: "macOS の時計横に表示されます。システム指標ごとにオフ、テキスト、チャートを選べます。",
            .clockAreaCompactMode: "状態値をコンパクト表示",
            .clockAreaCompactModeDetail: "選択した場合だけ、アイコンと値をより詰めたメニューバー表示にします。",
            .clockAreaSplitGroups: "状態グループを分離",
            .clockAreaSplitGroupsDetail: "実験的機能: メイン、システム、AI を分離します。macOS は空きスペースを残したり、他のメニューバー項目を隠したりする場合があります。",
            .clockAreaTextBold: "時計横テキストを太字",
            .clockAreaTextSize: "時計横テキストサイズ",
            .spillGlance: "Spill グランス",
            .spillGlanceDetail: "今日の合計、作業タイプ、選択した AI ツールを、移動可能な一つの横長ガラス表示にまとめます。",
            .showSpillGlance: "Spill グランスを表示",
            .spillGlanceDisplay: "表示方法",
            .spillGlanceDisplayAll: "すべて",
            .spillGlanceDisplayTicker: "ティッカー",
            .spillGlanceReactiveRotation: "反応型で表示",
            .spillGlanceReactiveRotationDetail: "いま変わったものだけを流し、落ち着いたら今日の合計に戻ります。オフにすると一定間隔で全体を巡回します。",
            .spillGlanceShowInFullScreen: "フルスクリーンでも表示",
            .spillGlanceShowInFullScreenDetail: "フルスクリーンアプリを覆わないよう、初期設定ではオフです。",
            .spillGlanceWorkRotation: "作業タイプを切り替える",
            .spillGlanceWorkRotationDetail: "Work 枠が作業タイプを切り替えるようにします。反応型で表示ではいま動いたタイプを表示し、オフにするとティッカーが今日の作業タイプを順番に巡回します。この項目をオフにすると使用量が最も多いタイプだけを表示します。",
            .spillGlanceCodex: "Codex",
            .spillGlanceClaude: "Claude",
            .spillGlanceAntigravity: "Antigravity",
            .layout: "レイアウト",
            .decimals: "CPU/MEM 小数",
            .highlight: "高使用率",
            .inline: "横",
            .stacked: "縦",
            .text: "テキスト",
            .chart: "チャート",
            .iconOnly: "アイコンのみ",
            .bundleID: "Bundle ID",
            .bundle: "バンドル",
            .executable: "実行ファイル",
            .pid: "PID",
            .appBundleLaunch: "アプリバンドル起動",
            .axTrusted: "AX 信頼済み"
    ]
}
