import Foundation

extension AppL10n {
    static let appJapaneseTextPart3: [AppTextKey: String] = [
            .showInMenuBar: "メニューバーに表示",
            .noItemsDetected: "検出項目はありません。",
            .selectedHiddenSummary: "選択 %d件、非表示 %d件",
            .activeSavedSummary: "有効 %d件、保存済み %d件",
            .selectedSummary: "選択 %d件",
            .clear: "消去",
            .usage: "使用量",
            .available: "利用可能",
            .user: "ユーザー",
            .system: "システム",
            .nice: "Nice",
            .idleLabel: "アイドル",
            .cores: "コア",
            .peakCore: "ピークコア",
            .sample: "サンプル",
            .state: "状態",
            .used: "使用中",
            .free: "空き",
            .active: "アクティブ",
            .inactive: "非アクティブ",
            .wired: "Wired",
            .compressed: "圧縮済み",
            .total: "合計",
            .budget: "予算",
            .unified: "統合",
            .lowPower: "低電力",
            .headless: "ヘッドレス",
            .removable: "取り外し可能",
            .receive: "受信",
            .upload: "アップロード",
            .interfaces: "インターフェイス",
            .receivedTotal: "総受信",
            .uploadedTotal: "総アップロード",
            .status: "状態",
            .detail: "詳細",
            .next: "次",
            .model: "モデル",
            .version: "バージョン",
            .source: "ソース",
            .yes: "はい",
            .no: "いいえ",
            .normal: "通常",
            .warning: "警告",
            .unavailable: "利用不可",
            .cpuActiveIdle: "%@ アクティブ / %@ アイドル",
            .waitingForSample: "サンプル待機中",
            .availableOfTotal: "%@ 利用可能 / 合計 %@",
            .externalPower: "外部電源",
            .charging: "充電中",
            .onPower: "電源接続中",
            .onBattery: "バッテリー使用中",
            .updateCheckingTitle: "アップデート確認中",
    ]
}
