import Foundation

extension AppL10n {
    static let appEnglishTextPart3: [AppTextKey: String] = [
            .showInMenuBar: "Show in menu bar",
            .noItemsDetected: "No items detected.",
            .selectedHiddenSummary: "%d selected, %d hidden",
            .activeSavedSummary: "%d active, %d saved",
            .selectedSummary: "%d selected",
            .clear: "Clear",
            .usage: "Usage",
            .available: "Available",
            .user: "User",
            .system: "System",
            .nice: "Nice",
            .idleLabel: "Idle",
            .cores: "Cores",
            .peakCore: "Peak Core",
            .sample: "Sample",
            .state: "State",
            .used: "Used",
            .free: "Free",
            .active: "Active",
            .inactive: "Inactive",
            .wired: "Wired",
            .compressed: "Compressed",
            .total: "Total",
            .budget: "Budget",
            .unified: "Unified",
            .lowPower: "Low Power",
            .headless: "Headless",
            .removable: "Removable",
            .receive: "Receive",
            .upload: "Upload",
            .interfaces: "Interfaces",
            .receivedTotal: "Received Total",
            .uploadedTotal: "Uploaded Total",
            .status: "Status",
            .detail: "Detail",
            .next: "Next",
            .model: "Model",
            .version: "Version",
            .source: "Source",
            .yes: "Yes",
            .no: "No",
            .normal: "Normal",
            .warning: "Warning",
            .unavailable: "Unavailable",
            .cpuActiveIdle: "%@ active / %@ idle",
            .waitingForSample: "Waiting for sample",
            .availableOfTotal: "%@ available of %@",
            .externalPower: "External Power",
            .charging: "Charging",
            .onPower: "On Power",
            .onBattery: "On Battery",
            .updateCheckingTitle: "Checking Updates",
    ]
}
