import Foundation

extension AppL10n {
    static let appKoreanTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "최신 상태",
            .updateAvailableTitle: "%@ 업데이트",
            .updateRequiresMacOSTitle: "macOS 업데이트 필요",
            .updateTitle: "업데이트",
            .updateNow: "지금 업데이트",
            .copyInstallCommand: "설치 명령 복사",
            .copied: "복사됨",
            .settings: "설정",
            .close: "닫기",
            .lookingForLatestRelease: "최신 릴리스 확인 중",
            .spillVersionCurrent: "Spill %@ 최신 상태",
            .inAppUpdateReady: "앱 내 업데이트 준비됨",
            .signedInstallerPackage: "서명된 설치 패키지",
            .manualInstaller: "수동 설치 프로그램",
            .versionNeedsMacOS: "버전 %@은 macOS %@ 필요",
            .updateHTTPFailedFormat: "업데이트 매니페스트 요청이 HTTP %d로 실패했습니다.",
            .invalidLatestVersionFormat: "업데이트 매니페스트의 최신 버전이 올바르지 않습니다: %@.",
            .invalidMacOSVersionFormat: "업데이트 매니페스트의 macOS 버전이 올바르지 않습니다: %@.",
            .updateDecodingFailedFormat: "업데이트 매니페스트를 해석할 수 없습니다: %@",
            .missingMacOSDownloadAsset: "최신 GitHub 릴리스에 Spill macOS 다운로드 에셋이 없습니다.",
            .triggerDrop: "물방울",
            .triggerDropSubtitle: "작은 물방울 심볼을 사용합니다.",
            .triggerSymbolizedS: "S 심볼",
            .triggerSymbolizedSSubtitle: "Spill S를 심볼화한 마크를 사용합니다.",
            .serviceStatusAccessibility: "서비스 상태 %@",
            .noDetail: "상세 없음",
            .noNotchCandidates: "노치 후보 없음",
            .nearNotchEstimate: "노치 근처 추정",
            .notScannedYet: "아직 스캔하지 않음",
            .accessibilityNotTrusted: "이 Spill 빌드에 손쉬운 사용 권한이 없습니다. 권한을 부여한 뒤 다시 확인하거나 개인정보 보호 설정에서 이 앱을 제거한 뒤 다시 추가하세요.",
            .refreshQueued: "현재 스캔이 끝나면 새로고침합니다.",
            .scanningMenuBarItems: "메뉴 막대 항목 스캔 중...",
            .refreshingMenuBarItems: "메뉴 막대 항목 새로고침 중...",
            .selectedItemUnavailable: "선택한 메뉴 막대 항목을 더 이상 사용할 수 없습니다.",
            .performedPrimaryAction: "선택한 메뉴 막대 항목의 기본 액션을 실행했습니다.",
            .pressFailedFormat: "선택한 메뉴 막대 항목을 누를 수 없습니다. AX 결과: %d.",
            .cachedResultUnchanged: " 이전 결과와 같습니다.",
            .noMenuBarItemsFoundFormat: "메뉴 막대 항목을 찾지 못했습니다. 앱 %d개, 메뉴 막대 영역 %d개, 보조 경로 %d개, 대체 경로 %d개, 확인한 항목 %d개를 확인했습니다.%@",
            .detectedNoNotchFormat: "메뉴 막대 항목 %d개를 찾았습니다. 메뉴 막대 영역 %d개를 확인했고 노치와 겹칠 가능성이 있는 항목은 없습니다.%@",
            .detectedNearNotchFormat: "메뉴 막대 항목 %d개를 찾았고, 노치 근처로 보이는 항목은 %d개입니다.%@",
            .pin: "고정",
            .unpin: "고정 해제",
            .pinnedFormat: "%@ 고정됨",
            .unpinnedFormat: "%@ 고정 해제됨",
            .pinInSpill: "Spill에 고정",
            .unpinFromSpill: "Spill에서 고정 해제",
            .showInSpill: "Spill에 표시",
            .hideInSpill: "Spill에서 숨김",
            .openedFormat: "%@ 열림",
            .unavailableFormat: "%@ 사용 불가",
            .permissionRequiredFormat: "%@ 권한 필요",
            .unsupportedFormat: "%@ 지원 안 함",
    ]
}
