import Foundation

extension AppL10n {
    static let appEnglishTextPart2: [AppTextKey: String] = [
            .servicesFromOfficialSources: "%d services checked",
            .openDashboardToFetchStatus: "Fetch service status",
            .notFetched: "Not fetched",
            .officialStatusFetchedOnOpen: "Service status is fetched only when this view opens.",
            .lastChecked: "Last checked %@ (%@).",
            .justNow: "just now",
            .minutesAgo: "%dm ago",
            .hoursAgo: "%dh ago",
            .operational: "Operational",
            .degraded: "Degraded",
            .outage: "Outage",
            .maintenance: "Maintenance",
            .unknown: "Unknown",
            .serverOK: "Server OK",
            .maint: "Maint",
            .checking: "Checking",
            .serverStatus: "Server Status",
            .server: "Server",
            .serverStatusPendingHelp: "Server status will appear after the next official status check.",
            .fetchOfficialServiceStatus: "Click to fetch official service status details.",
            .serverStatusNoIssues: "Server status %@",
            .serverStatusWithIssues: "Server status %@ with %d issue(s)",
            .clickForPerServiceDetails: "Click for per-service details.",
            .openStatusPage: "Open %@ status page",
            .tokenMetering: "Token Metering",
            .local: "Local",
            .webSyncEnabled: "Web sync on",
            .tokens: "tokens",
            .details: "Details",
            .openLocalTokenMeteringDetails: "Open Spill - AI Token Metering",
            .tokenMeteringAccessibility: "Token Metering, %@ local tokens",
            .tokenMeteringSetupTitle: "Set up Token Metering",
            .tokenMeteringSetupDetail: "Open Settings > Token Metering and follow the setup steps. This preview keeps local data intact.",
            .tokenMeteringSettings: "Token Metering Settings",
            .menuBarTokenDisplayModeDaily: "Today Only",
            .menuBarTokenDisplayModeTotal: "Total Only",
            .menuBarTokenDisplayModeDailyAndTotal: "Today & Total",
            .menuBarTokenDisplayModeCycle: "Auto-cycle",
            .openSetupPrompt: "Open setup instructions",
            .noTaskSplit: "No work type data",
            .noSourceSplit: "No detail data",
            .eventsSummary: "%@ records / %@ / %@",
            .aiProcessSummary: "%d running / %d processes",
            .process: "Process",
            .processes: "Processes",
            .cpu: "CPU",
            .memory: "Memory",
            .windows: "WINDOWS",
            .menuBar: "MENU BAR",
            .noFocusedWindow: "No Focused Window",
            .positions: "POSITIONS",
            .utilities: "UTILITIES",
    ]
}
