import Foundation

extension AppL10n {
    static let appJapaneseTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "最新",
            .updateAvailableTitle: "%@ を更新",
            .updateRequiresMacOSTitle: "macOS アップデートが必要",
            .updateTitle: "アップデート",
            .updateNow: "今すぐ更新",
            .copyInstallCommand: "インストールコマンドをコピー",
            .copied: "コピー済み",
            .settings: "設定",
            .close: "閉じる",
            .lookingForLatestRelease: "最新リリースを確認中",
            .spillVersionCurrent: "Spill %@ は最新です",
            .inAppUpdateReady: "アプリ内アップデート準備完了",
            .signedInstallerPackage: "署名済みインストーラーパッケージ",
            .manualInstaller: "手動インストーラー",
            .versionNeedsMacOS: "バージョン %@ には macOS %@ が必要",
            .updateHTTPFailedFormat: "アップデートマニフェストのリクエストが HTTP %d で失敗しました。",
            .invalidLatestVersionFormat: "アップデートマニフェストの最新バージョンが無効です: %@。",
            .invalidMacOSVersionFormat: "アップデートマニフェストの macOS バージョンが無効です: %@。",
            .updateDecodingFailedFormat: "アップデートマニフェストをデコードできませんでした: %@",
            .missingMacOSDownloadAsset: "最新の GitHub リリースに Spill macOS ダウンロードアセットがありません。",
            .triggerDrop: "しずく",
            .triggerDropSubtitle: "コンパクトなしずくシンボルを使用します。",
            .triggerSymbolizedS: "S マーク",
            .triggerSymbolizedSSubtitle: "シンボル化した Spill の S マークを使用します。",
            .serviceStatusAccessibility: "サービス状態 %@",
            .noDetail: "詳細なし",
            .openedFormat: "%@ を開きました",
            .unavailableFormat: "%@ は利用不可",
            .permissionRequiredFormat: "%@ 権限が必要",
            .unsupportedFormat: "%@ は未対応",
    ]
}
