import Foundation

extension AppL10n {
    static let appJapaneseTextPart2: [AppTextKey: String] = [
            .servicesFromOfficialSources: "%d件のサービスを確認",
            .openDashboardToFetchStatus: "サービス状態を取得",
            .notFetched: "未取得",
            .officialStatusFetchedOnOpen: "サービス状態はこの画面を開いたときだけ取得します。",
            .lastChecked: "最終確認 %@ (%@)。",
            .justNow: "たった今",
            .minutesAgo: "%d分前",
            .hoursAgo: "%d時間前",
            .operational: "正常",
            .degraded: "低下",
            .outage: "障害",
            .maintenance: "メンテナンス",
            .unknown: "不明",
            .serverOK: "サーバー正常",
            .maint: "メンテ",
            .checking: "確認中",
            .serverStatus: "サーバー状態",
            .server: "サーバー",
            .serverStatusPendingHelp: "次の公式状態確認後にサーバー状態が表示されます。",
            .fetchOfficialServiceStatus: "クリックして公式サービス状態の詳細を取得します。",
            .serverStatusNoIssues: "サーバー状態 %@",
            .serverStatusWithIssues: "サーバー状態 %@、問題 %d件",
            .clickForPerServiceDetails: "サービス別詳細を見るにはクリックしてください。",
            .openStatusPage: "%@ のステータスページを開く",
            .serviceGuidanceCheckingTitle: "公式サービスを確認中",
            .serviceGuidanceCheckingDetail: "Spill が共有ローカル状態を更新するまで、この画面を開いたままにしてください。",
            .serviceGuidanceNotFetchedTitle: "公式サービス状態を確認",
            .serviceGuidanceNotFetchedDetail: "ローカルツールを調べる前に、更新して公式サービスを比較してください。",
            .serviceGuidanceHealthyTitle: "公式サービスは正常です",
            .serviceGuidanceHealthyDetail: "ツールが動作しない場合は、ローカルプロセスと設定の詳細を確認してください。",
            .serviceGuidanceIssueTitleOne: "公式サービスの問題 %d件",
            .serviceGuidanceIssueTitleMany: "公式サービスの問題 %d件",
            .serviceGuidanceIssueDetail: "ローカル設定を変更する前に、影響を受けているサービスを確認してください。",
            .serviceGuidanceUnavailableTitle: "公式状態をすべて確認できませんでした",
            .serviceGuidanceUnavailableDetail: "更新するか、該当プロバイダーのステータスページで詳細を確認してください。",
            .tokenMetering: "トークン計測",
            .local: "ローカル",
            .webSyncEnabled: "Web同期オン",
            .tokens: "トークン",
            .details: "詳細",
            .openLocalTokenMeteringDetails: "Spill - AI Token Metering を開く",
            .tokenMeteringAccessibility: "トークン計測、ローカルトークン %@",
            .tokenMeteringSetupTitle: "トークン計測を設定",
            .tokenMeteringSetupDetail: "設定 > トークン計測を開き、手順に従って接続します。このプレビューはローカルデータを保持します。",
            .tokenMeteringSettings: "トークン計測設定",
            .menuBarTokenDisplayModeDaily: "今日のみ表示",
            .menuBarTokenDisplayModeTotal: "合計のみ表示",
            .menuBarTokenDisplayModeDailyAndTotal: "今日と合計を表示",
            .menuBarTokenDisplayModeCycle: "自動切り替え",
            .openSetupPrompt: "セットアップ手順を開く",
            .noTaskSplit: "作業タイプなし",
            .noSourceSplit: "詳細分類なし",
            .eventsSummary: "記録 %@件 / %@ / %@",
            .aiProcessSummary: "%d 実行中 / %d プロセス",
            .process: "プロセス",
            .processes: "プロセス",
            .cpu: "CPU",
            .memory: "メモリ",
            .windows: "ウィンドウ",
            .menuBar: "メニューバー",
            .noFocusedWindow: "フォーカス中のウィンドウなし",
            .positions: "位置",
            .utilities: "ユーティリティ",
    ]
}
