import Foundation

extension AppL10n {
    static let appKoreanTextPart2: [AppTextKey: String] = [
            .servicesFromOfficialSources: "서비스 %d개 확인됨",
            .openDashboardToFetchStatus: "서비스 상태 가져오기",
            .notFetched: "가져오지 않음",
            .officialStatusFetchedOnOpen: "서비스 상태는 이 화면을 열 때만 가져옵니다.",
            .lastChecked: "마지막 확인 %@ (%@).",
            .justNow: "방금",
            .minutesAgo: "%d분 전",
            .hoursAgo: "%d시간 전",
            .operational: "정상",
            .degraded: "저하",
            .outage: "장애",
            .maintenance: "점검",
            .unknown: "알 수 없음",
            .serverOK: "서버 정상",
            .maint: "점검",
            .checking: "확인 중",
            .serverStatus: "서버 상태",
            .server: "서버",
            .serverStatusPendingHelp: "다음 공식 상태 확인 후 서버 상태가 표시됩니다.",
            .fetchOfficialServiceStatus: "클릭해서 공식 서비스 상태 상세를 가져옵니다.",
            .serverStatusNoIssues: "서버 상태 %@",
            .serverStatusWithIssues: "서버 상태 %@, 이슈 %d개",
            .clickForPerServiceDetails: "서비스별 상세를 보려면 클릭하세요.",
            .openStatusPage: "%@ 상태 페이지 열기",
            .tokenMetering: "토큰 미터링",
            .local: "로컬",
            .webSyncEnabled: "웹 동기화 켜짐",
            .tokens: "토큰",
            .details: "상세",
            .openLocalTokenMeteringDetails: "Spill - AI Token Metering 열기",
            .tokenMeteringAccessibility: "토큰 미터링, 로컬 토큰 %@개",
            .tokenMeteringSetupTitle: "토큰 미터링 설정",
            .tokenMeteringSetupDetail: "설정 > 토큰 미터링에서 안내를 따라 연결하세요. 이 미리보기는 로컬 데이터를 유지합니다.",
            .tokenMeteringSettings: "토큰 미터링 설정",
            .menuBarTokenDisplayModeDaily: "오늘만 표시",
            .menuBarTokenDisplayModeTotal: "합계만 표시",
            .menuBarTokenDisplayModeDailyAndTotal: "오늘/합계 표시",
            .menuBarTokenDisplayModeCycle: "자동 전환",
            .openSetupPrompt: "설치 안내 열기",
            .noTaskSplit: "작업 유형 없음",
            .noSourceSplit: "세부 분류 없음",
            .eventsSummary: "기록 %@개 / %@ / %@",
            .aiProcessSummary: "%d개 실행 / 프로세스 %d개",
            .process: "프로세스",
            .processes: "프로세스",
            .cpu: "CPU",
            .memory: "메모리",
            .windows: "윈도우",
            .menuBar: "메뉴 막대",
            .noFocusedWindow: "포커스된 윈도우 없음",
            .positions: "위치",
            .utilities: "유틸리티",
    ]
}
