import Foundation

extension AppL10n {
    static let appKoreanTextPart3: [AppTextKey: String] = [
            .showInMenuBar: "메뉴 막대에 표시",
            .noItemsDetected: "감지된 항목 없음",
            .selectedHiddenSummary: "선택 %d개, 숨김 %d개",
            .activeSavedSummary: "활성 %d개, 저장됨 %d개",
            .selectedSummary: "선택 %d개",
            .clear: "지우기",
            .usage: "사용량",
            .available: "사용 가능",
            .user: "사용자",
            .system: "시스템",
            .nice: "Nice",
            .idleLabel: "유휴",
            .cores: "코어",
            .peakCore: "피크 코어",
            .sample: "샘플",
            .state: "상태",
            .used: "사용됨",
            .free: "여유",
            .active: "활성",
            .inactive: "비활성",
            .wired: "Wired",
            .compressed: "압축됨",
            .total: "합계",
            .budget: "예산",
            .unified: "통합",
            .lowPower: "저전력",
            .headless: "헤드리스",
            .removable: "분리 가능",
            .receive: "수신",
            .upload: "업로드",
            .interfaces: "인터페이스",
            .receivedTotal: "총 수신",
            .uploadedTotal: "총 업로드",
            .status: "상태",
            .detail: "상세",
            .next: "다음",
            .model: "모델",
            .version: "버전",
            .source: "소스",
            .yes: "예",
            .no: "아니오",
            .normal: "정상",
            .warning: "경고",
            .unavailable: "사용 불가",
            .cpuActiveIdle: "%@ 활성 / %@ 유휴",
            .waitingForSample: "샘플 대기 중",
            .availableOfTotal: "%@ 사용 가능 / 전체 %@",
            .externalPower: "외부 전원",
            .charging: "충전 중",
            .onPower: "전원 연결",
            .onBattery: "배터리 사용",
            .updateCheckingTitle: "업데이트 확인 중",
    ]
}
