import Foundation

extension AppL10n {
    static let appEnglishTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "Up to Date",
            .updateAvailableTitle: "Update %@",
            .updateRequiresMacOSTitle: "Update Requires macOS",
            .updateTitle: "Update",
            .updateNow: "Update now",
            .copyInstallCommand: "Copy install command",
            .copied: "Copied",
            .settings: "Settings",
            .close: "Close",
            .lookingForLatestRelease: "Looking for the latest release",
            .spillVersionCurrent: "Spill %@ is current",
            .inAppUpdateReady: "In-app update ready",
            .signedInstallerPackage: "Signed installer package",
            .manualInstaller: "Manual installer",
            .versionNeedsMacOS: "Version %@ needs macOS %@",
            .updateHTTPFailedFormat: "Update manifest request failed with HTTP %d.",
            .invalidLatestVersionFormat: "Update manifest has an invalid latest version: %@.",
            .invalidMacOSVersionFormat: "Update manifest has an invalid macOS version: %@.",
            .updateDecodingFailedFormat: "Update manifest could not be decoded: %@",
            .missingMacOSDownloadAsset: "Latest GitHub release does not include a Spill macOS download asset.",
            .triggerDrop: "Drop",
            .triggerDropSubtitle: "Uses the compact droplet symbol.",
            .triggerSymbolizedS: "Symbolized S",
            .triggerSymbolizedSSubtitle: "Uses the symbolized Spill S mark.",
            .serviceStatusAccessibility: "Service status %@",
            .noDetail: "No detail",
            .openedFormat: "Opened %@",
            .unavailableFormat: "%@ unavailable",
            .permissionRequiredFormat: "%@ permission required",
            .unsupportedFormat: "%@ unsupported",
    ]
}
