import Foundation

extension AppL10n {
    static let appKoreanTextPart1: [AppTextKey: String] = [
            .showSpillPanel: "Spill 패널 보기",
            .hideSpillPanel: "Spill 패널 숨기기",
            .openLocalTokenDashboard: "Spill - AI Token Metering 열기",
            .refreshMenuBarItems: "대시보드 데이터 새로고침",
            .checkForUpdates: "업데이트 확인...",
            .preferences: "설정...",
            .quitSpill: "Spill 종료",
            .shortcut: "단축키",
            .tokenMeteringLocalDashboard: "Spill - AI Token Metering",
            .triggerLoad: "트리거 상태",
            .caffeineChipStart: "카페인: 클릭해서 시작",
            .caffeineChipStop: "클릭해서 중지",
            .caffeineOnUntilStopped: "중지할 때까지 켬",
            .caffeineOnUntilStoppedDisplayMaySleep: "중지할 때까지 켬, 디스플레이는 잠들 수 있음",
            .caffeineRemaining: "%@ 남음",
            .caffeineRemainingDisplayMaySleep: "%@ 남음, 디스플레이는 잠들 수 있음",
            .scanning: "스캔 중",
            .onboardingPreviewTitle: "온보딩 미리보기",
            .ready: "준비됨",
            .refreshingActions: "액션 새로고침 중",
            .on: "켬",
            .idle: "대기",
            .off: "끔",
            .chooseCaffeineDuration: "카페인 지속 시간 선택",
            .stopCaffeine: "카페인 중지",
            .startDuration: "%@ 시작",
            .power: "전원",
            .caffeine: "카페인",
            .caffeineOff: "카페인 꺼짐",
            .caffeineUntilStopped: "카페인 - 중지할 때까지 켬",
            .caffeineUntilStoppedDisplayMaySleep: "카페인 - 중지할 때까지 켬 - 디스플레이는 잠들 수 있음",
            .caffeineRemainingHelp: "카페인 - %@ 남음",
            .caffeineRemainingDisplayMaySleepHelp: "카페인 - %@ 남음 - 디스플레이는 잠들 수 있음",
            .couldNotStartCaffeine: "카페인을 시작할 수 없습니다.",
            .couldNotKeepDisplayAwake: "디스플레이를 깨어 있게 유지할 수 없습니다.",
            .statusDetails: "상태 상세",
            .refreshForceHelp: "공식 서비스 상태를 새로 확인합니다.",
            .checkingOfficialSources: "공식 상태 확인 중",
            .fetchedWhenOpen: "열 때 가져옴",
    ]
}
