import Foundation

extension AppL10n {
    static let appJapaneseTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "最新",
            .updateAvailableTitle: "%@ を更新",
            .updateRequiresMacOSTitle: "macOS アップデートが必要",
            .updateTitle: "アップデート",
            .updateNow: "今すぐ更新",
            .copyInstallCommand: "インストールコマンドをコピー",
            .copied: "コピー済み",
            .settings: "設定",
            .close: "閉じる",
            .lookingForLatestRelease: "最新リリースを確認中",
            .spillVersionCurrent: "Spill %@ は最新です",
            .inAppUpdateReady: "アプリ内アップデート準備完了",
            .signedInstallerPackage: "署名済みインストーラーパッケージ",
            .manualInstaller: "手動インストーラー",
            .versionNeedsMacOS: "バージョン %@ には macOS %@ が必要",
            .updateHTTPFailedFormat: "アップデートマニフェストのリクエストが HTTP %d で失敗しました。",
            .invalidLatestVersionFormat: "アップデートマニフェストの最新バージョンが無効です: %@。",
            .invalidMacOSVersionFormat: "アップデートマニフェストの macOS バージョンが無効です: %@。",
            .updateDecodingFailedFormat: "アップデートマニフェストをデコードできませんでした: %@",
            .missingMacOSDownloadAsset: "最新の GitHub リリースに Spill macOS ダウンロードアセットがありません。",
            .triggerDrop: "しずく",
            .triggerDropSubtitle: "コンパクトなしずくシンボルを使用します。",
            .triggerSymbolizedS: "S マーク",
            .triggerSymbolizedSSubtitle: "シンボル化した Spill の S マークを使用します。",
            .serviceStatusAccessibility: "サービス状態 %@",
            .noDetail: "詳細なし",
            .noNotchCandidates: "ノッチ候補なし",
            .nearNotchEstimate: "ノッチ付近の推定",
            .notScannedYet: "まだスキャンしていません。",
            .accessibilityNotTrusted: "この Spill ビルドにはアクセシビリティ権限が許可されていません。権限を付与した後に再確認するか、プライバシー設定でこのアプリを削除して再追加してください。",
            .refreshQueued: "現在のスキャンが完了したら更新します。",
            .scanningMenuBarItems: "メニューバー項目をスキャン中...",
            .refreshingMenuBarItems: "メニューバー項目を更新中...",
            .selectedItemUnavailable: "選択したメニューバー項目は利用できなくなりました。",
            .performedPrimaryAction: "選択したメニューバー項目の主要アクションを実行しました。",
            .pressFailedFormat: "選択したメニューバー項目を押せませんでした。AX の戻り値: %d。",
            .cachedResultUnchanged: " 前回の結果と同じです。",
            .noMenuBarItemsFoundFormat: "メニューバー項目が見つかりません。アプリ %d件、メニューバー領域 %d件、補助経路 %d件、代替経路 %d件、確認した項目 %d件を確認しました。%@",
            .detectedNoNotchFormat: "メニューバー項目 %d件を見つけました。メニューバー領域 %d件を確認し、ノッチと重なる可能性のある項目はありません。%@",
            .detectedNearNotchFormat: "メニューバー項目 %d件を見つけ、ノッチ付近と思われる項目は %d件です。%@",
            .pin: "固定",
            .unpin: "固定解除",
            .pinnedFormat: "%@ を固定しました",
            .unpinnedFormat: "%@ の固定を解除しました",
            .pinInSpill: "Spill に固定",
            .unpinFromSpill: "Spill から固定解除",
            .showInSpill: "Spill に表示",
            .hideInSpill: "Spill で非表示",
            .openedFormat: "%@ を開きました",
            .unavailableFormat: "%@ は利用不可",
            .permissionRequiredFormat: "%@ 権限が必要",
            .unsupportedFormat: "%@ は未対応",
    ]
}
