import Foundation

extension AppL10n {
    static let appEnglishTextPart1: [AppTextKey: String] = [
            .showSpillPanel: "Show Spill Panel",
            .hideSpillPanel: "Hide Spill Panel",
            .openLocalTokenDashboard: "Open Spill - AI Token Metering",
            .refreshMenuBarItems: "Refresh Menu Bar Items",
            .checkForUpdates: "Check for Updates...",
            .preferences: "Preferences...",
            .quitSpill: "Quit Spill",
            .shortcut: "Shortcut",
            .tokenMeteringLocalDashboard: "Spill - AI Token Metering",
            .menuBarItemCount: "%d menu bar item(s)",
            .triggerLoad: "Trigger status",
            .caffeineChipStart: "Caffeine: click to start",
            .caffeineChipStop: "click to stop",
            .caffeineOnUntilStopped: "on until stopped",
            .caffeineOnUntilStoppedDisplayMaySleep: "on until stopped, display may sleep",
            .caffeineRemaining: "%@ remaining",
            .caffeineRemainingDisplayMaySleep: "%@ remaining, display may sleep",
            .accessibilityRequired: "Accessibility required",
            .scanning: "Scanning",
            .noActionsReady: "No actions ready",
            .onboardingPreviewTitle: "Onboarding preview",
            .onboardingPreviewDetail: "Preview the first-run dashboard without changing local actions or usage data.",
            .ready: "Ready",
            .permissionNeeded: "Permission needed",
            .refreshingActions: "Refreshing actions",
            .pinned: "%d pinned",
            .actionsReady: "%d actions ready",
            .ax: "AX",
            .ok: "OK",
            .need: "Need",
            .scan: "Scan",
            .on: "On",
            .idle: "Idle",
            .items: "Items",
            .time: "Time",
            .off: "Off",
            .chooseCaffeineDuration: "Choose Caffeine Duration",
            .stopCaffeine: "Stop Caffeine",
            .startDuration: "Start %@",
            .power: "Power",
            .caffeine: "Caffeine",
            .caffeineOff: "Caffeine Off",
            .caffeineUntilStopped: "Caffeine - on until stopped",
            .caffeineUntilStoppedDisplayMaySleep: "Caffeine - on until stopped - display may sleep",
            .caffeineRemainingHelp: "Caffeine - %@ remaining",
            .caffeineRemainingDisplayMaySleepHelp: "Caffeine - %@ remaining - display may sleep",
            .couldNotStartCaffeine: "Could not start Caffeine.",
            .couldNotKeepDisplayAwake: "Could not keep the display awake.",
            .statusDetails: "Status Details",
            .refreshForceHelp: "Refresh official service status.",
            .checkingOfficialSources: "Checking official status",
            .fetchedWhenOpen: "Fetched when this opens",
    ]
}
