import Foundation

extension AppL10n {
    static let appEnglishTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "Up to Date",
            .updateAvailableTitle: "Update %@",
            .updateRequiresMacOSTitle: "Update Requires macOS",
            .updateTitle: "Update",
            .updateNow: "Update now",
            .copyInstallCommand: "Copy install command",
            .copied: "Copied",
            .settings: "Settings",
            .close: "Close",
            .lookingForLatestRelease: "Looking for the latest release",
            .spillVersionCurrent: "Spill %@ is current",
            .inAppUpdateReady: "In-app update ready",
            .signedInstallerPackage: "Signed installer package",
            .manualInstaller: "Manual installer",
            .versionNeedsMacOS: "Version %@ needs macOS %@",
            .updateHTTPFailedFormat: "Update manifest request failed with HTTP %d.",
            .invalidLatestVersionFormat: "Update manifest has an invalid latest version: %@.",
            .invalidMacOSVersionFormat: "Update manifest has an invalid macOS version: %@.",
            .updateDecodingFailedFormat: "Update manifest could not be decoded: %@",
            .missingMacOSDownloadAsset: "Latest GitHub release does not include a Spill macOS download asset.",
            .triggerDrop: "Drop",
            .triggerDropSubtitle: "Uses the compact droplet symbol.",
            .triggerSymbolizedS: "Symbolized S",
            .triggerSymbolizedSSubtitle: "Uses the symbolized Spill S mark.",
            .serviceStatusAccessibility: "Service status %@",
            .noDetail: "No detail",
            .noNotchCandidates: "No Notch Candidates",
            .nearNotchEstimate: "near notch estimate",
            .notScannedYet: "Not scanned yet.",
            .accessibilityNotTrusted: "Accessibility is not trusted for this Spill build. Recheck after granting it, or remove and re-add this app in Privacy settings.",
            .refreshQueued: "Refresh queued while the current scan finishes.",
            .scanningMenuBarItems: "Scanning menu bar items...",
            .refreshingMenuBarItems: "Refreshing menu bar items...",
            .selectedItemUnavailable: "The selected menu bar item is no longer available.",
            .performedPrimaryAction: "Performed primary action for the selected menu bar item.",
            .pressFailedFormat: "Could not press the selected menu bar item. AX returned %d.",
            .cachedResultUnchanged: " Cached result unchanged.",
            .noMenuBarItemsFoundFormat: "No menu bar items found. Scanned %d apps, %d menu bar roots (%d extras, %d fallback), %d candidate elements.%@",
            .detectedNoNotchFormat: "Detected %d menu bar item(s). Scanned %d menu bar roots; no notch overlap candidate found.%@",
            .detectedNearNotchFormat: "Detected %d menu bar item(s), %d near the notch estimate.%@",
            .pin: "Pin",
            .unpin: "Unpin",
            .pinnedFormat: "Pinned %@",
            .unpinnedFormat: "Unpinned %@",
            .pinInSpill: "Pin in Spill",
            .unpinFromSpill: "Unpin from Spill",
            .showInSpill: "Show in Spill",
            .hideInSpill: "Hide in Spill",
            .openedFormat: "Opened %@",
            .unavailableFormat: "%@ unavailable",
            .permissionRequiredFormat: "%@ permission required",
            .unsupportedFormat: "%@ unsupported",
    ]
}
