import Foundation

extension AppL10n {
    static let appJapaneseTextPart1: [AppTextKey: String] = [
            .showSpillPanel: "Spill パネルを表示",
            .hideSpillPanel: "Spill パネルを隠す",
            .openLocalTokenDashboard: "Spill - AI Token Metering を開く",
            .refreshMenuBarItems: "メニューバー項目を更新",
            .checkForUpdates: "アップデートを確認...",
            .preferences: "設定...",
            .quitSpill: "Spill を終了",
            .shortcut: "ショートカット",
            .tokenMeteringLocalDashboard: "Spill - AI Token Metering",
            .menuBarItemCount: "メニューバー項目 %d件",
            .triggerLoad: "トリガー状態",
            .caffeineChipStart: "カフェイン: クリックして開始",
            .caffeineChipStop: "クリックして停止",
            .caffeineOnUntilStopped: "停止するまでオン",
            .caffeineOnUntilStoppedDisplayMaySleep: "停止するまでオン、ディスプレイはスリープ可能",
            .caffeineRemaining: "残り %@",
            .caffeineRemainingDisplayMaySleep: "残り %@、ディスプレイはスリープ可能",
            .accessibilityRequired: "アクセシビリティが必要",
            .scanning: "スキャン中",
            .noActionsReady: "準備済みアクションなし",
            .onboardingPreviewTitle: "オンボーディングプレビュー",
            .onboardingPreviewDetail: "ローカルのアクションと使用量データを変えずに初回ダッシュボードを確認します。",
            .ready: "準備完了",
            .permissionNeeded: "権限が必要",
            .refreshingActions: "アクションを更新中",
            .pinned: "固定 %d件",
            .actionsReady: "アクション %d件が準備完了",
            .ax: "AX",
            .ok: "OK",
            .need: "必要",
            .scan: "スキャン",
            .on: "オン",
            .idle: "待機",
            .items: "項目",
            .time: "時刻",
            .off: "オフ",
            .chooseCaffeineDuration: "カフェイン時間を選択",
            .stopCaffeine: "カフェインを停止",
            .startDuration: "%@ を開始",
            .power: "電源",
            .caffeine: "カフェイン",
            .caffeineOff: "カフェイン オフ",
            .caffeineUntilStopped: "カフェイン - 停止するまでオン",
            .caffeineUntilStoppedDisplayMaySleep: "カフェイン - 停止するまでオン - ディスプレイはスリープ可能",
            .caffeineRemainingHelp: "カフェイン - 残り %@",
            .caffeineRemainingDisplayMaySleepHelp: "カフェイン - 残り %@ - ディスプレイはスリープ可能",
            .couldNotStartCaffeine: "カフェインを開始できませんでした。",
            .couldNotKeepDisplayAwake: "ディスプレイを起動状態に保てませんでした。",
            .statusDetails: "状態詳細",
            .refreshForceHelp: "公式サービス状態を更新します。",
            .checkingOfficialSources: "公式ステータスを確認中",
            .fetchedWhenOpen: "開いたときに取得",
    ]
}
