import Foundation

extension AppL10n {
    static let appKoreanTextPart4: [AppTextKey: String] = [
            .updateUpToDateTitle: "최신 상태",
            .updateAvailableTitle: "%@ 업데이트",
            .updateRequiresMacOSTitle: "macOS 업데이트 필요",
            .updateTitle: "업데이트",
            .updateNow: "지금 업데이트",
            .copyInstallCommand: "설치 명령 복사",
            .copied: "복사됨",
            .settings: "설정",
            .close: "닫기",
            .lookingForLatestRelease: "최신 릴리스 확인 중",
            .spillVersionCurrent: "Spill %@ 최신 상태",
            .inAppUpdateReady: "앱 내 업데이트 준비됨",
            .signedInstallerPackage: "서명된 설치 패키지",
            .manualInstaller: "수동 설치 프로그램",
            .versionNeedsMacOS: "버전 %@은 macOS %@ 필요",
            .updateHTTPFailedFormat: "업데이트 매니페스트 요청이 HTTP %d로 실패했습니다.",
            .invalidLatestVersionFormat: "업데이트 매니페스트의 최신 버전이 올바르지 않습니다: %@.",
            .invalidMacOSVersionFormat: "업데이트 매니페스트의 macOS 버전이 올바르지 않습니다: %@.",
            .updateDecodingFailedFormat: "업데이트 매니페스트를 해석할 수 없습니다: %@",
            .missingMacOSDownloadAsset: "최신 GitHub 릴리스에 Spill macOS 다운로드 에셋이 없습니다.",
            .triggerDrop: "물방울",
            .triggerDropSubtitle: "작은 물방울 심볼을 사용합니다.",
            .triggerSymbolizedS: "S 심볼",
            .triggerSymbolizedSSubtitle: "Spill S를 심볼화한 마크를 사용합니다.",
            .serviceStatusAccessibility: "서비스 상태 %@",
            .noDetail: "상세 없음",
            .openedFormat: "%@ 열림",
            .unavailableFormat: "%@ 사용 불가",
            .permissionRequiredFormat: "%@ 권한 필요",
            .unsupportedFormat: "%@ 지원 안 함",
    ]
}
