import Foundation

extension AppL10n {
    static let appJapaneseTextPart1: [AppTextKey: String] = [
            .showSpillPanel: "Spill パネルを表示",
            .hideSpillPanel: "Spill パネルを隠す",
            .openLocalTokenDashboard: "Spill - AI Token Metering を開く",
            .refreshMenuBarItems: "ダッシュボードのデータを更新",
            .checkForUpdates: "アップデートを確認...",
            .preferences: "設定...",
            .quitSpill: "Spill を終了",
            .shortcut: "ショートカット",
            .tokenMeteringLocalDashboard: "Spill - AI Token Metering",
            .triggerLoad: "トリガー状態",
            .caffeineChipStart: "カフェイン: クリックして開始",
            .caffeineChipStop: "クリックして停止",
            .caffeineOnUntilStopped: "停止するまでオン",
            .caffeineOnUntilStoppedDisplayMaySleep: "停止するまでオン、ディスプレイはスリープ可能",
            .caffeineRemaining: "残り %@",
            .caffeineRemainingDisplayMaySleep: "残り %@、ディスプレイはスリープ可能",
            .scanning: "スキャン中",
            .onboardingPreviewTitle: "オンボーディングプレビュー",
            .ready: "準備完了",
            .refreshingActions: "アクションを更新中",
            .on: "オン",
            .idle: "待機",
            .off: "オフ",
            .chooseCaffeineDuration: "カフェイン時間を選択",
            .stopCaffeine: "カフェインを停止",
            .startDuration: "%@ を開始",
            .power: "電源",
            .caffeine: "カフェイン",
            .caffeineOff: "カフェイン オフ",
            .caffeineUntilStopped: "カフェイン - 停止するまでオン",
            .caffeineUntilStoppedDisplayMaySleep: "カフェイン - 停止するまでオン - ディスプレイはスリープ可能",
            .caffeineRemainingHelp: "カフェイン - 残り %@",
            .caffeineRemainingDisplayMaySleepHelp: "カフェイン - 残り %@ - ディスプレイはスリープ可能",
            .couldNotStartCaffeine: "カフェインを開始できませんでした。",
            .couldNotKeepDisplayAwake: "ディスプレイを起動状態に保てませんでした。",
            .statusDetails: "状態詳細",
            .refreshForceHelp: "公式サービス状態を更新します。",
            .checkingOfficialSources: "公式ステータスを確認中",
            .fetchedWhenOpen: "開いたときに取得",
    ]
}
