import Foundation

extension AppTextKey {
    static let lookingForLatestRelease = Self(rawValue: "lookingForLatestRelease")
    static let spillVersionCurrent = Self(rawValue: "spillVersionCurrent")
    static let inAppUpdateReady = Self(rawValue: "inAppUpdateReady")
    static let signedInstallerPackage = Self(rawValue: "signedInstallerPackage")
    static let manualInstaller = Self(rawValue: "manualInstaller")
    static let versionNeedsMacOS = Self(rawValue: "versionNeedsMacOS")
    static let updateHTTPFailedFormat = Self(rawValue: "updateHTTPFailedFormat")
    static let invalidLatestVersionFormat = Self(rawValue: "invalidLatestVersionFormat")
    static let invalidMacOSVersionFormat = Self(rawValue: "invalidMacOSVersionFormat")
    static let updateDecodingFailedFormat = Self(rawValue: "updateDecodingFailedFormat")
    static let missingMacOSDownloadAsset = Self(rawValue: "missingMacOSDownloadAsset")
    static let triggerDrop = Self(rawValue: "triggerDrop")
    static let triggerDropSubtitle = Self(rawValue: "triggerDropSubtitle")
    static let triggerSymbolizedS = Self(rawValue: "triggerSymbolizedS")
    static let triggerSymbolizedSSubtitle = Self(rawValue: "triggerSymbolizedSSubtitle")
    static let serviceStatusAccessibility = Self(rawValue: "serviceStatusAccessibility")
    static let noDetail = Self(rawValue: "noDetail")
    static let openedFormat = Self(rawValue: "openedFormat")
    static let unavailableFormat = Self(rawValue: "unavailableFormat")
    static let permissionRequiredFormat = Self(rawValue: "permissionRequiredFormat")
    static let unsupportedFormat = Self(rawValue: "unsupportedFormat")
    static let windowLeft = Self(rawValue: "windowLeft")
    static let windowRight = Self(rawValue: "windowRight")
    static let windowTop = Self(rawValue: "windowTop")
    static let windowBottom = Self(rawValue: "windowBottom")
    static let windowCenter = Self(rawValue: "windowCenter")
    static let windowMaximize = Self(rawValue: "windowMaximize")
    static let windowTopLeft = Self(rawValue: "windowTopLeft")
    static let windowTopRight = Self(rawValue: "windowTopRight")
    static let windowBottomLeft = Self(rawValue: "windowBottomLeft")
    static let windowBottomRight = Self(rawValue: "windowBottomRight")
    static let windowPreviousDisplay = Self(rawValue: "windowPreviousDisplay")
    static let windowNextDisplay = Self(rawValue: "windowNextDisplay")
}
