import Foundation

extension AppTextKey {
    static let showSpillPanel = Self(rawValue: "showSpillPanel")
    static let hideSpillPanel = Self(rawValue: "hideSpillPanel")
    static let openLocalTokenDashboard = Self(rawValue: "openLocalTokenDashboard")
    static let refreshMenuBarItems = Self(rawValue: "refreshMenuBarItems")
    static let checkForUpdates = Self(rawValue: "checkForUpdates")
    static let preferences = Self(rawValue: "preferences")
    static let quitSpill = Self(rawValue: "quitSpill")
    static let shortcut = Self(rawValue: "shortcut")
    static let tokenMeteringLocalDashboard = Self(rawValue: "tokenMeteringLocalDashboard")
    static let triggerLoad = Self(rawValue: "triggerLoad")
    static let caffeineChipStart = Self(rawValue: "caffeineChipStart")
    static let caffeineChipStop = Self(rawValue: "caffeineChipStop")
    static let caffeineOnUntilStopped = Self(rawValue: "caffeineOnUntilStopped")
    static let caffeineOnUntilStoppedDisplayMaySleep = Self(rawValue: "caffeineOnUntilStoppedDisplayMaySleep")
    static let caffeineRemaining = Self(rawValue: "caffeineRemaining")
    static let caffeineRemainingDisplayMaySleep = Self(rawValue: "caffeineRemainingDisplayMaySleep")
    static let scanning = Self(rawValue: "scanning")
    static let onboardingPreviewTitle = Self(rawValue: "onboardingPreviewTitle")
    static let ready = Self(rawValue: "ready")
    static let refreshingActions = Self(rawValue: "refreshingActions")
    static let on = Self(rawValue: "on")
    static let idle = Self(rawValue: "idle")
    static let off = Self(rawValue: "off")
    static let chooseCaffeineDuration = Self(rawValue: "chooseCaffeineDuration")
    static let stopCaffeine = Self(rawValue: "stopCaffeine")
    static let startDuration = Self(rawValue: "startDuration")
    static let power = Self(rawValue: "power")
    static let caffeine = Self(rawValue: "caffeine")
    static let caffeineOff = Self(rawValue: "caffeineOff")
    static let caffeineUntilStopped = Self(rawValue: "caffeineUntilStopped")
    static let caffeineUntilStoppedDisplayMaySleep = Self(rawValue: "caffeineUntilStoppedDisplayMaySleep")
    static let caffeineRemainingHelp = Self(rawValue: "caffeineRemainingHelp")
    static let caffeineRemainingDisplayMaySleepHelp = Self(rawValue: "caffeineRemainingDisplayMaySleepHelp")
    static let couldNotStartCaffeine = Self(rawValue: "couldNotStartCaffeine")
    static let couldNotKeepDisplayAwake = Self(rawValue: "couldNotKeepDisplayAwake")
    static let statusDetails = Self(rawValue: "statusDetails")
    static let refreshForceHelp = Self(rawValue: "refreshForceHelp")
    static let checkingOfficialSources = Self(rawValue: "checkingOfficialSources")
    static let fetchedWhenOpen = Self(rawValue: "fetchedWhenOpen")
    static let servicesFromOfficialSources = Self(rawValue: "servicesFromOfficialSources")
    static let openDashboardToFetchStatus = Self(rawValue: "openDashboardToFetchStatus")
    static let notFetched = Self(rawValue: "notFetched")
}
